### ISSUE TITLE
Unique projectIds for projects that are created from an template

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang-message-sdk#105]
### Context

If templates are copied (e.g. starter kits) all have the same project id.

### Proposal

Regenerate a new projectId if a new repo is created from a template.

**Comment by NiklasBuchfink** [comment]
Possible issues could be:

* dependent on .git in directory (if used to generate the projectId)
* forks are also used to contribute and should have the same projectId<br>-> wouldn't be a problem, if everything is handled by Lix and change requests/suggestions are created by default

**Comment by felixhaeberle** [comment]
comment on the current project_id challenges

**Comment by samuelstroschein** [comment]
**Proposal** <br><br>Ignore this problem. We have to come up with an id system that works in a distributed manner. Will take time. Just ignore it for now.

* inlang directories will become their own repo. you will run into the same problem again
* its unclear if a fork or copy is a different or the same project. we have no consensus here.
* the problem is minor. if we have more users than we actually think -> great.
