### ISSUE TITLE
requirements lint rule per message/ per variant configuration

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-message-sdk#5]
## Problem

Lint rules are all or nothing. There is no way to ignore a warning coming from a lint rule just for a specific message.

This is especially annoying with the "duplicate pattern" lint rule which has a lot of false positives.

This has been a common complaint

* [https://discord.com/channels/897438559458430986/1220012877768032389](https://discord.com/channels/897438559458430986/1220012877768032389)
* [https://github.com/opral/monorepo/discussions/2408](https://github.com/opral/monorepo/discussions/2408)

## Proposal

Some way to ignore lint warnings for specific messages. 

This would likely require annotating messages with metadata.

cc @felix.haeberle

**Comment by samuelstroschein** [comment]
@loris.sigrist nice feature. came up several times. I propose to create a project out of this because it requires multiple teams to collaborate/is not a one off issue. 

* storing per message configuration
* storing per variant configuration
* updating the upcoming `<inlang-settings>` component to make this configurable
* updating the upcoming `<inlang-message-editor>` component to "one click" ignore lints for a message/variant
* show in `<inlang-message-editor>` component that a lint rule is ignored for a message/variant

**Comment by samuelstroschein** [comment]
@loris.sigrist agree to turn this into a project? 

Maybe leave this issue open for external collaborators to upvote this issue & discuss.

**Comment by samuelstroschein** [comment]
moved to lix validation rules [lix validation rules](https://linear.app/opral/project/lix-validation-rules-bdf46c532aa1)
