### ISSUE TITLE
File lock contention fails on large files - lock is held while events propagate.

### ISSUE THREAD

**Issue by jldec** [opral/inlang-message-sdk#54]
MESDK-92

### Context

Observed with 10k load test and then running machine translate in another process

The watcher (which doesn't write) grabbed the lock for so long that the cli translate process overruled it after max retries.

![Screenshot 2024-05-10 at 08.56.59.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/c9004de6-7993-4c64-bc77-0b511bf6454c/4754f0d9-5f03-48d2-a385-f0131c8f1a68?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9jOTAwNGRlNi03OTkzLTRjNjQtYmM3Ny0wYjUxMWJmNjQ1NGMvNDc1NGYwZDktNWYwMy00OGQyLWEzODUtZjAxMzFjOGYxYTY4IiwiaWF0IjoxNzE1MzQ1OTczLCJleHAiOjMzMjg1OTA1OTczfQ.EjeRH3xNYAG6pWouWMkOm7Cx6r9L-GYjwO4xg8XzWDA "=2760x")

### Proposal

**Comment by jldec** [comment]
repro'ed again and discussed 1:1

1. contention is not happening during save - only during followup loads. (so no danger of file corruption)
2. the save (writer) process with subscriptions holds the lock while propagating all events (e.g. to getAll() subscribers), and this takes a long time. 

Question: Can we release the lock earler (after save, but before triggering all events)?

**Comment by martin-lysk** [comment]
As long as reactivityMap is in the core of the SDK - One option here would be to use a solid [batch](https://docs.solidjs.com/reference/reactive-utilities/batch) to reduce signal productions during message loading - this should reduce $KEYS and $VALUES trigger in ReactivityMap. If we consider that we should also back to await 0 instead of setTimeout(0…) to avoid a side effect from UI kicking in from macroTasks loop.

**Comment by martin-lysk** [comment]
As an alternative I would suggest as a next stop towards to [MESDK-67](https://linear.app/opral/issue/MESDK-67/remove-solid-from-in-memory-core-message-store)  :  

Decuple solid and introduce a messageStore that propagates changes using the delagate pattern to the a reactiveMessageQuery which would than serve as our thin layer to ui. This would allow us to remove reactivityMap from messageStore and we could use the delegate to propagate batched changes.

**Comment by jldec** [comment]
@martin.lysk1, you're right - this lock problem is tightly coupled with the reactivity implementation.

The question is whether we fix it now for the old plugins, or focus on implementing experimental persistence for our v2 message structure first.

I would prefer to do the latter, but I'm open for discussion if anyone disagrees.

**Comment by martin-lysk** [comment]
The root cause of this particular issue is the missing stale detection of the lock. read performance should be tackled separate ticket. I briefly discussed this with jan and we decided to add the 'ax' flag option to the memoryFS and to the nodishFileSystem type. That allows us to use lockfile instead of lockfolder and we will also be able to detect stale lock files (compare: [LIX-63](https://linear.app/opral/issue/LIX-63/implement-wx-flag-for-writefile-api)) keeping this in the backlock for now.
