### ISSUE TITLE
Consistent use of either `languageTag` or `locale`

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-sdk#94]
We use languageTag in the settings and I thought it is the standard across the sdk.<br>No I see locale. Was this added on purpose? What should I use in the component.<br><br>I think we should agree on one.

**Comment by jldec** [comment]
The new MessageBundle type identifes the locale of a message using a `locale` property with a `LanguageTag` type. 

This is consistent with the usage of "locale" in the ICU messageformat repos. e.g. [https://github.com/search?q=repo%3Amessageformat%2Fmessageformat locale](https://github.com/search?q=repo%3Amessageformat%2Fmessageformat%20locale&type=code) 

This also matches the usage of "locale" in JavaScript [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/language)

I don't really see a problem with continuing to use the `LanguageTag`type as described in [https://www.ietf.org/rfc/bcp/bcp47.txt](https://www.ietf.org/rfc/bcp/bcp47.txt) . We pulled in this type from the @inlang/language-tag package in \[PR # 2700\]([https://github.com/opral/monorepo/pull/2700#discussion_r1594837300](https://github.com/opral/monorepo/pull/2700#discussion_r1594837300)) because we prefer not use separately maintained packages where possible.<br><br>While I agree that it would be nice to use the same `locale` property everywhere, modifying the project settings format was not in scope at this time.

<br>cc: @martin.lysk1 @loris.sigrist @samuel.stroschein <br>Please chime in if you had a different intent in [PR #2655](https://github.com/opral/monorepo/pull/2655) or disagree

**Comment by samuelstroschein** [comment]
if we switch to "locale", then language tag as property name should be deprecated everywhere and replaced by "locale" to avoid confusion, including in the settings.json
