### ISSUE TITLE
Expose Error types that are part of the External API

### ISSUE THREAD

**Issue by LorisSigrist** [opral/inlang-message-sdk#99]
### Context

`project.errors()` returns a union of a bunch of different errors, that may have one of many prototypes. However, when you get an error it's impossible to react to which error it is exactly since you cant access the prototypes to do type-checks.

Eg: 

```
for(const error of project.errors()) {
  //apps can't do this because ModuleError is not exported
  if(error instanceof ModuleError) console.warn("Error in", error.module)
}
```

### Proposal

Expose the Error types that are part of the External API

**Comment by samuelstroschein** [comment]
<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/2f2d442a-acb0-4783-a94b-9fc34e724fd3/0fa8d83a-5b78-400c-b011-31e6e1354ebc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yZjJkNDQyYS1hY2IwLTQ3ODMtYTk0Yi05ZmMzNGU3MjRmZDMvMGZhOGQ4M2EtNWI3OC00MDBjLWIwMTEtMzFlNmUxMzU0ZWJjIiwiaWF0IjoxNzE4NzA0MTQzLCJleHAiOjMzMjg5MjY0MTQzfQ.EuDPIMzzZfDm50x0AMyg64SXax50O5TyqkQC_s8RH4c " alt="CleanShot 2024-06-18 at 11.48.10@2x.png" width="682" height="324" />

true. should likely be `export * from "./errors.js` 

@loris.sigrist would it be good to speed up iterations on the inlang sdk by submitting prs for small issues like this instead of opening one?
